name: quota-test
on: [push]
jobs:
  stall:
    name: Stall for 10 minutes ${{ matrix.trial_number }}
    runs-on: macos-15
    strategy:
      matrix:
        trial_number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Stall for 10 minutes
        run: for x in $(seq 31); do date; sleep 20; done
